# Generated by Django 5.2.4 on 2025-08-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('npi', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('credential', models.CharField(blank=True, max_length=50, null=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('grouping', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTaxonomy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docfinder.provider')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docfinder.taxonomy')),
            ],
        ),
    ]
